version: '2'
services:
  node:
    image: malaslt/easygrow-local-rpi:latest
    restart: always
    privileged: true
    depends_on:
        - db
    links:
        - db
    devices:
        - "/dev/ttyAMA0:/dev/ttyAMA0"
        - "/dev/mem:/dev/mem"
  db:
    image: partlab/ubuntu-arm-mongodb:latest
    restart: always
    volumes:
        - ./data:/data/db

# Can not find ARM7 version  
#  mongo-express:
#    image: mongo-express
#    depends_on:
#        - db
#    links:
#        - db:mongo
#    ports:
#        - "8081:8081"
#    restart: always