version: '2'
services:
  node:
    image: malaslt/easygrow-local-rpi:latest
    restart: always
    privileged: true
    depends_on:
        - db
    links:
        - db
    devices:
        - "/dev/ttyAMA0:/dev/ttyAMA0"
        - "/dev/mem:/dev/mem"
  db:
    image: malaslt/mongodb-rpi
    restart: always
    volumes:
        - ./data:/data/db

  mongo-express:
    image: malaslt/mongo-express-arm:latest
    depends_on:
        - db
    links:
        - db:mongo
    ports:
        - "8081:8081"
    restart: always
    environment:
        - ME_CONFIG_BASICAUTH_USERNAME=pirate
        - ME_CONFIG_BASICAUTH_PASSWORD=hypriot