version: '2'
services:
  node:
    image: malaslt/easygrow-local-rpi:latest
    #restart: always
    depends_on:
        - db
    links:
        - db
  db:
    image: mongo:latest
    #restart: always
    volumes:
        - ./data:/data/db
  
  mongo-express:
    image: mongo-express
    depends_on:
        - db
    links:
        - db:mongo
    ports:
        - "8081:8081"